/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author theag
 */
public class AddCases extends javax.swing.JFrame {

    private myDBCon db;
    ResultSet rs;
    ResultSet ComboBoxes;
    ArrayList<Integer> Criminals = new ArrayList<>();
    ArrayList<Integer> Officers = new ArrayList<>();
    ArrayList<Integer> Crimes = new ArrayList<>();
    ArrayList<Integer> Stations = new ArrayList<>();
    public AddCases(myDBCon db) throws SQLException
    {
        this.db = db;   
        initComponents();
        disableErrorLabels();
        removeLabels();
        
        rs = db.executeQuery("SELECT CriminalID, fname, lname from criminal order by criminalID ASC");      
        while(rs.next())
        {
            Criminals.add(rs.getInt("criminalID"));
            CriminalIDCmbBox.addItem(rs.getString("fname") + rs.getString("lname"));
        }
        
        ComboBoxes = db.executeQuery("SELECT officerID, fname, lname, stationid from officer order by officerID ASC");
        
        while(ComboBoxes.next())
        {
            Officers.add(ComboBoxes.getInt("officerID"));
            Stations.add(ComboBoxes.getInt("stationid"));
            OfficerIDCmbBox.addItem(ComboBoxes.getString("fname") + " " +  ComboBoxes.getString("lname"));
        }
        
        rs = db.executeQuery("SELECT CrimeID, name from Crime order by CrimeID ASC");
        
        while(rs.next())
        {
            Crimes.add(rs.getInt("CrimeID"));
            CrimeIDCmbBox.addItem(rs.getString("name"));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CaseIDLabel3 = new javax.swing.JLabel();
        CaseIDLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CaseIDText = new javax.swing.JTextPane();
        DateError = new javax.swing.JLabel();
        CaseIDLabel1 = new javax.swing.JLabel();
        CriminalIDCmbBox = new javax.swing.JComboBox<>();
        CaseIDLabel4 = new javax.swing.JLabel();
        OfficerIDCmbBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescriptionText = new javax.swing.JTextPane();
        CrimeIDCmbBox = new javax.swing.JComboBox<>();
        hiredateLabel = new javax.swing.JLabel();
        CaseIDLabel2 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        DateText = new javax.swing.JTextPane();
        CaseIDError = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        DescriptionError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setText("Add Cases");

        CaseIDLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CaseIDLabel3.setText("Crime ID:");

        CaseIDLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CaseIDLabel.setText("Case ID:");

        jScrollPane1.setViewportView(CaseIDText);

        DateError.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        DateError.setForeground(new java.awt.Color(255, 0, 0));
        DateError.setText("ERROR LABEL");

        CaseIDLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CaseIDLabel1.setText("Description:");

        CriminalIDCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriminalIDCmbBoxActionPerformed(evt);
            }
        });

        CaseIDLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CaseIDLabel4.setText("Officer ID:");

        OfficerIDCmbBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OfficerIDCmbBoxItemStateChanged(evt);
            }
        });
        OfficerIDCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficerIDCmbBoxActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(DescriptionText);

        hiredateLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        hiredateLabel.setText("Recorded Date:");

        CaseIDLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CaseIDLabel2.setText("Criminal ID:");

        jScrollPane7.setViewportView(DateText);

        CaseIDError.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        CaseIDError.setForeground(new java.awt.Color(255, 0, 0));
        CaseIDError.setText("ERROR LABEL");

        buttonAdd.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        buttonAdd.setText("ADD");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        DescriptionError.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        DescriptionError.setForeground(new java.awt.Color(255, 0, 0));
        DescriptionError.setText("ERROR LABEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CaseIDLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DescriptionError, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CaseIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(CaseIDError, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hiredateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateError, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CaseIDLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CriminalIDCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CaseIDLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CrimeIDCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CaseIDLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(OfficerIDCmbBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CaseIDLabel)
                    .addComponent(CaseIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CaseIDLabel1)
                    .addComponent(DescriptionError)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaseIDLabel2)
                    .addComponent(CriminalIDCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaseIDLabel4)
                    .addComponent(OfficerIDCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaseIDLabel3)
                    .addComponent(CrimeIDCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hiredateLabel)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateError))
                .addGap(18, 18, 18)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    boolean isValidData() throws SQLException
    {
        boolean flag = true;
        
        //check for caseID (empty, length greater than 4)
        if(CaseIDText.getText().trim().isEmpty() || CaseIDText.getText().length() > 4 || !Validation.isInteger(CaseIDText.getText().trim()))
        {
            if(CaseIDText.getText().trim().isEmpty())
            {
                CaseIDError.setText("This field cannot be empty");
               
            }
            else if(CaseIDText.getText().length() > 4)
            {
                CaseIDError.setText("The length is at most 4 digits");
            }
            else if(!Validation.isInteger(CaseIDText.getText().trim()))
            {
                CaseIDError.setText("Invalid. Must be integer");
            }
            CaseIDError.setVisible(true);
            flag = false;
        }
        
        rs = db.executeQuery("SELECT caseID, criminalID FROM case WHERE caseID = " + "'" + CaseIDText.getText() + "'" + "AND CriminalID = " + "'" + Criminals.get(CriminalIDCmbBox.getSelectedIndex()) + "'" + "AND CrimeID = " + "'" + Crimes.get(CrimeIDCmbBox.getSelectedIndex()) + "'");
        if(rs.next())
        {
            CaseIDError.setText("The set (Case ID, Criminal ID, Crime ID) already exists");
            CaseIDError.setVisible(true);
            flag = false;
        }
         
        //check for description (empty, greater than 100)
        if(DescriptionText.getText().trim().isEmpty() || DescriptionText.getText().length() > 100)
        {
            if(DescriptionText.getText().trim().isEmpty())
            {
                DescriptionError.setText("The field should not be empty");
                
            }
            else if(DescriptionText.getText().length() > 100)
            {
                DescriptionError.setText("The length should be at most 100 characters");
            }
            DescriptionError.setVisible(true);
            flag = false;
        }
        
        //check for date (empty, format -WIP-)
        if(DateText.getText().trim().isEmpty())
        {
            DateError.setText("This field should not be empty");
            DateError.setVisible(true);
            flag = false;
        }
        
        
        
        
        return flag;
    }
    
    void disableErrorLabels()
    {
        CaseIDError.setText("");
        DescriptionError.setText("");
        DateError.setText("");
        
    }
    
    void removeLabels()
    {
        CaseIDText.setText("");
        DescriptionText.setText("");
        DateText.setText("");
    }
    
    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
           
           disableErrorLabels();
          
        try {
            if(isValidData())
            {   
                
                
                
                System.out.println("VALID 1");
                db.setupPrepStatement("INSERT INTO case (caseID, description, criminalID, crimeID, officerID, recorded_date, stationID) VALUES(?,?,?,?,?,?,?)");
                System.out.println("VALID 2");
                db.getPrepStatement().setInt(1,Integer.parseInt(CaseIDText.getText()));
                System.out.println("VALID 3");
                db.getPrepStatement().setString(2,DescriptionText.getText());
                System.out.println("VALID 4");
                db.getPrepStatement().setInt(3, Criminals.get(CriminalIDCmbBox.getSelectedIndex()));
                System.out.println("VALID 5");
                db.getPrepStatement().setInt(4, Crimes.get(CrimeIDCmbBox.getSelectedIndex()));
                System.out.println("VALID 6");
                db.getPrepStatement().setInt(5, Officers.get(OfficerIDCmbBox.getSelectedIndex()));
                System.out.println("VALID 7");
                db.getPrepStatement().setString(6, DateText.getText());
                System.out.println("VALID 8");
                db.getPrepStatement().setInt(7, Stations.get(OfficerIDCmbBox.getSelectedIndex()));
                System.out.println("VALID 9");
                int result = this.db.executePrepUpdate();
                System.out.println("VALID 10");
                if (result > 0) {
                    System.out.println("VALID 11");
                    javax.swing.JLabel label = new javax.swing.JLabel("new case Added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                }
                
                      
                removeLabels();
            }
        } catch (SQLException ex) {
            //Logger.getLogger(EditCases.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_buttonAddActionPerformed

    private void CriminalIDCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriminalIDCmbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriminalIDCmbBoxActionPerformed

    private void OfficerIDCmbBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OfficerIDCmbBoxItemStateChanged
      
        
    }//GEN-LAST:event_OfficerIDCmbBoxItemStateChanged

    private void OfficerIDCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfficerIDCmbBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OfficerIDCmbBoxActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CaseIDError;
    private javax.swing.JLabel CaseIDLabel;
    private javax.swing.JLabel CaseIDLabel1;
    private javax.swing.JLabel CaseIDLabel2;
    private javax.swing.JLabel CaseIDLabel3;
    private javax.swing.JLabel CaseIDLabel4;
    private javax.swing.JTextPane CaseIDText;
    private javax.swing.JComboBox<String> CrimeIDCmbBox;
    private javax.swing.JComboBox<String> CriminalIDCmbBox;
    private javax.swing.JLabel DateError;
    private javax.swing.JTextPane DateText;
    private javax.swing.JLabel DescriptionError;
    private javax.swing.JTextPane DescriptionText;
    private javax.swing.JComboBox<String> OfficerIDCmbBox;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JLabel hiredateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
