/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author theag
 */
public class DisplayCriminal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String SQ;
    private myDBCon db;
    ResultSet rs;
    public DisplayCriminal(myDBCon db, String SQL) {
        this.db = db;
        this.SQ = SQL;
        initComponents();
        getNewData();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FnameLabel = new javax.swing.JLabel();
        disaplyCriminalLabel = new javax.swing.JLabel();
        LnameLabel = new javax.swing.JLabel();
        CriminalIDLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Picture = new javax.swing.JLabel();
        LnameText = new javax.swing.JTextField();
        FnameText = new javax.swing.JTextField();
        CriminalIDText = new javax.swing.JTextField();
        Weight = new javax.swing.JLabel();
        WeightText = new javax.swing.JTextField();
        LastNameLabel1 = new javax.swing.JLabel();
        HeightText = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        AgeText = new javax.swing.JTextField();
        buttonNext = new javax.swing.JButton();
        buttonPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FnameLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        FnameLabel.setText("First Name:");

        disaplyCriminalLabel.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        disaplyCriminalLabel.setText("Criminal Display");

        LnameLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        LnameLabel.setText("Last Name:");

        CriminalIDLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CriminalIDLabel.setText("Criminal ID:");

        LnameText.setEditable(false);
        LnameText.setBackground(new java.awt.Color(255, 255, 255));

        FnameText.setEditable(false);
        FnameText.setBackground(new java.awt.Color(255, 255, 255));

        CriminalIDText.setEditable(false);
        CriminalIDText.setBackground(new java.awt.Color(255, 255, 255));

        Weight.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        Weight.setText("Weight:");

        WeightText.setEditable(false);
        WeightText.setBackground(new java.awt.Color(255, 255, 255));
        WeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightTextActionPerformed(evt);
            }
        });

        LastNameLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        LastNameLabel1.setText("Height:");

        HeightText.setEditable(false);
        HeightText.setBackground(new java.awt.Color(255, 255, 255));
        HeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightTextActionPerformed(evt);
            }
        });

        AgeLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        AgeLabel.setText("Age:");

        AgeText.setEditable(false);
        AgeText.setBackground(new java.awt.Color(255, 255, 255));

        buttonNext.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        buttonNext.setText("NEXT >>");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        buttonPrev.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        buttonPrev.setText("<< PREV");
        buttonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LnameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LnameText))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FnameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FnameText))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CriminalIDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CriminalIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LastNameLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(HeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(AgeLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(AgeText))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Weight)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(WeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(disaplyCriminalLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(buttonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disaplyCriminalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CriminalIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CriminalIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Weight)
                            .addComponent(WeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastNameLabel1)
                            .addComponent(HeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void getNewData() {

        try {
            String str;
            System.out.println(SQ);
            if(SQ != null) {rs = db.executeQuery(SQ);}            
            else {rs = db.executeQuery("SELECT * from criminal ORDER BY criminalID ASC");}
            
            // populate rest of fields
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Error loading Fields.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void populateFields() {
        try {
            CriminalIDText.setText(rs.getString("criminalID"));
            FnameText.setText(rs.getString("fname"));
            LnameText.setText(rs.getString("lname"));
            AgeText.setText(rs.getString("age"));
            WeightText.setText(rs.getString("weight"));
            HeightText.setText(rs.getString("height"));
            if(rs.getBlob("picture") != null)
            {
                new Thread(new Runnable()
                {
                    @Override
                    public void run()
                    {
                        File pic = new File("current.png");
                try {
                    
                    FileOutputStream output = new FileOutputStream(pic);
                    InputStream input = null;
                            try {
                                input = rs.getBinaryStream("picture");
                            } catch (SQLException ex) {
                                Logger.getLogger(DisplayCriminal.class.getName()).log(Level.SEVERE, null, ex);
                            }
                    byte buffer[] = new byte[1024];
                    try {
                        while(input.read(buffer)>0)
                        {
                            output.write(buffer);
                        }
                        String path = pic.getAbsolutePath();
                        ImageIcon myimg = new ImageIcon(path);
                        Image img = myimg.getImage();
                        Image newImg= img.getScaledInstance(Picture.getWidth(), Picture.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon finalImage = new ImageIcon(newImg);
                        Picture.setIcon(finalImage);
                        
                    } catch (IOException ex) {
                        Logger.getLogger(DisplayCriminal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DisplayCriminal.class.getName()).log(Level.SEVERE, null, ex);
                }
                    }
                }).start();
                
            }
            else
            {
                Picture.setIcon(null);
            }
            
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(DisplayCriminal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void WeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightTextActionPerformed

    private void HeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightTextActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        try {
            if (!rs.isLast()) {

                rs.next();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(DisplayCriminal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonNextActionPerformed

    private void buttonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrevActionPerformed
        try {
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(DisplayCriminal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonPrevActionPerformed
    private void EnableDisableButtons()
    {      
        try {
            if (rs.isFirst()) {
                buttonPrev.setVisible(false);
            } else {
                buttonPrev.setVisible(true);
            }
            if (rs.isLast()) {
                buttonNext.setVisible(false);
            } else {
                buttonNext.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DisplayCriminal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeText;
    private javax.swing.JLabel CriminalIDLabel;
    private javax.swing.JTextField CriminalIDText;
    private javax.swing.JLabel FnameLabel;
    private javax.swing.JTextField FnameText;
    private javax.swing.JTextField HeightText;
    private javax.swing.JLabel LastNameLabel1;
    private javax.swing.JLabel LnameLabel;
    private javax.swing.JTextField LnameText;
    private javax.swing.JLabel Picture;
    private javax.swing.JLabel Weight;
    private javax.swing.JTextField WeightText;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonPrev;
    private javax.swing.JLabel disaplyCriminalLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
