/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author theag
 */
public class EditCriminal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private myDBCon db;
    private ResultSet rs;
    File selectedFile = null;
    public EditCriminal(myDBCon db) {
        this.db = db;
        initComponents();
        clearErrorLabels();
        for(int i = 1; i <= 99; i++)
        {
            AgeCmbBox.addItem(""+i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        FirstNameText = new javax.swing.JTextPane();
        UpdateButton = new javax.swing.JButton();
        LastNameLabel = new javax.swing.JLabel();
        DeleteButton = new javax.swing.JButton();
        EditCriminalInfoLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        LastNameText = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchText = new javax.swing.JTextPane();
        searchButton = new javax.swing.JButton();
        CriminalIDLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CriminalIDText = new javax.swing.JTextPane();
        FirstNameLabel = new javax.swing.JLabel();
        SelectPicture = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        lbCriminalIDError = new javax.swing.JLabel();
        lblFnameError = new javax.swing.JLabel();
        HeightError = new javax.swing.JLabel();
        Weight = new javax.swing.JLabel();
        WeightText = new javax.swing.JTextField();
        LastNameLabel1 = new javax.swing.JLabel();
        AgeCmbBox = new javax.swing.JComboBox<>();
        HeightText = new javax.swing.JTextField();
        AgeLabel = new javax.swing.JLabel();
        lblLnameError = new javax.swing.JLabel();
        WeightError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane4.setViewportView(FirstNameText);

        UpdateButton.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        LastNameLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        LastNameLabel.setText("Last Name:");

        DeleteButton.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        EditCriminalInfoLabel.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        EditCriminalInfoLabel.setText("Edit Criminal Information");

        jScrollPane5.setViewportView(LastNameText);

        SearchText.setToolTipText("search criminal by ID"); // NOI18N
        jScrollPane1.setViewportView(SearchText);

        searchButton.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        CriminalIDLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        CriminalIDLabel.setText("Criminal ID:");

        jScrollPane2.setViewportView(CriminalIDText);

        FirstNameLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        FirstNameLabel.setText("First Name:");

        SelectPicture.setText("Select Picture");
        SelectPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectPictureActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("No Picture Selected");

        Reset.setText("Reset Picture");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        lbCriminalIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbCriminalIDError.setForeground(new java.awt.Color(255, 0, 0));
        lbCriminalIDError.setText("error label");

        lblFnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblFnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblFnameError.setText("error label");

        HeightError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        HeightError.setForeground(new java.awt.Color(255, 0, 0));
        HeightError.setText("error label");

        Weight.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        Weight.setText("Weight:");

        WeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightTextActionPerformed(evt);
            }
        });

        LastNameLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        LastNameLabel1.setText("Height:");

        HeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightTextActionPerformed(evt);
            }
        });

        AgeLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        AgeLabel.setText("Age:");

        lblLnameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblLnameError.setForeground(new java.awt.Color(255, 0, 0));
        lblLnameError.setText("error label");

        WeightError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        WeightError.setForeground(new java.awt.Color(255, 0, 0));
        WeightError.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(EditCriminalInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(searchButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FirstNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CriminalIDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCriminalIDError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblFnameError, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addComponent(lblLnameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SelectPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LastNameLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(HeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Weight)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(WeightText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AgeCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WeightError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HeightError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditCriminalInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CriminalIDLabel)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLabel)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCriminalIDError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFnameError)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLnameError)
                    .addComponent(LastNameLabel)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Weight)
                    .addComponent(WeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WeightError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LastNameLabel1)
                            .addComponent(HeightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectPicture)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeleteButton)
                            .addComponent(UpdateButton))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HeightError)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        try {
            

            if (isValidData()) {
                if(this.selectedFile == null)
                {
                    this.db.setupPrepStatement("UPDATE criminal SET fname = ?, lname = ?, weight = ?, height = ?, age = ? WHERE criminalID = ?");
                    this.db.getPrepStatement().setString(1, FirstNameText.getText().toUpperCase());
                    this.db.getPrepStatement().setString(2, LastNameText.getText().toUpperCase());                    
                    this.db.getPrepStatement().setInt(3,Integer.parseInt(WeightText.getText()));
                    this.db.getPrepStatement().setString(4, HeightText.getText());
                    this.db.getPrepStatement().setInt(5,Integer.parseInt(AgeCmbBox.getSelectedItem().toString()));
                    this.db.getPrepStatement().setString(6, CriminalIDText.getText());
                }
                else
                {
                    this.db.setupPrepStatement("UPDATE criminal SET fname = ?, lname = ?, , weight = ?, height = ?, age = ?, picture = ? WHERE criminalID = ?");
                    this.db.getPrepStatement().setString(1, FirstNameText.getText().toUpperCase());
                    this.db.getPrepStatement().setString(2, LastNameText.getText().toUpperCase());
                    this.db.getPrepStatement().setInt(3,Integer.parseInt(WeightText.getText()));
                    this.db.getPrepStatement().setString(4, HeightText.getText());
                    this.db.getPrepStatement().setInt(5,Integer.parseInt(AgeCmbBox.getSelectedItem().toString()));
                    try {
                        this.db.getPrepStatement().setBlob(6, new FileInputStream(this.selectedFile));
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(EditCriminal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.db.getPrepStatement().setString(7, CriminalIDText.getText());
                }
                
                
                
                
                int res = this.db.executePrepUpdate();
                if (res > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("crimnial updated successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    resetLabels();
                }
            
            } else {

                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, "Error updating Criminal. " + e.getMessage());

        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        try {
           this.db.setupPrepStatement("DELETE criminal WHERE criminalID = " + CriminalIDText.getText().trim());
            int result = this.db.executePrepUpdate();
            if (result > 0) {
                javax.swing.JLabel label = new javax.swing.JLabel("Criminal of ID: " + CriminalIDText.getText().trim() + " deleted successfully.");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                resetLabels();
            }


        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error Deleting Criminal.");

        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
         try {
            rs = db.executeQuery("SELECT * FROM criminal WHERE criminalID = " + "'" + SearchText.getText() + "'");
            if(rs.next())
            {
               CriminalIDText.setText(rs.getString("criminalID"));
               FirstNameText.setText(rs.getString("fname"));
               LastNameText.setText(rs.getString("lname"));
               AgeCmbBox.setSelectedItem(rs.getString("age"));
               WeightText.setText(rs.getString("weight"));
               HeightText.setText(rs.getString("height"));
               db.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditCases.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    
    void clearErrorLabels() {
        lbCriminalIDError.setText("");
        lblFnameError.setText("");
        HeightError.setText("");
        WeightError.setText("");
        lblLnameError.setText("");

    }
    
    void resetLabels()
    {
        CriminalIDText.setText("");
        FirstNameText.setText("");
        LastNameText.setText("");
        WeightText.setText("");
        HeightText.setText("");
        SearchText.setText("");
    }
    boolean isValidData() {
        boolean result = true;
        clearErrorLabels();

       

        if (CriminalIDText.getText().trim().isEmpty() || (CriminalIDText.getText().trim().length() > 4)) {
            if (CriminalIDText.getText().trim().isEmpty()) {
                lbCriminalIDError.setText("Invalid. Cannot be empty.");
            } else if ((CriminalIDText.getText().trim().length() > 4)) {
                lbCriminalIDError.setText("Invalid. cannot exceed 4 chars.");
            }

            lbCriminalIDError.setVisible(true);
            result = false;
        }

        if (FirstNameText.getText().trim().isEmpty() || (FirstNameText.getText().trim().length() > 25)) {
            if (FirstNameText.getText().trim().isEmpty()) {
                lblFnameError.setText("Invalid. Cannot be empty.");
            } else if ((FirstNameText.getText().trim().length() > 25)) {
                lblFnameError.setText("Invalid. cannot exceed 25 chars.");
            }

            lblFnameError.setVisible(true);
            result = false;
        }
        
        

        if (LastNameText.getText().trim().isEmpty() || (LastNameText.getText().trim().length() > 25)) {
            if (LastNameText.getText().trim().isEmpty())
            {
                lblLnameError.setText("Invalid. Cannot be empty.");
            } else if ((LastNameText.getText().trim().length() > 25))
            {
                lblLnameError.setText("Invalid. cannot exceed 25 chars.");
            }

            lblLnameError.setVisible(true);
            result = false;
        }
        
        if(HeightText.getText().trim().isEmpty() ||  HeightText.getText().length() > 7)
        {
            if(HeightText.getText().trim().isEmpty())
            {
                HeightError.setText("Invalid. Cannot be empty");
            }
            else if(HeightText.getText().length() > 3)
            {
                HeightError.setText("Invalid. Length cannot exceed 3 digits and 3 decimal points");
            }
            
            result = false;
        }
        
        if(WeightText.getText().trim().isEmpty() || WeightText.getText().length() > 8)
        {
            if(WeightText.getText().trim().isEmpty())
            {
                WeightError.setText("Invalid. Cannot be empty");
            }
            else if(WeightText.getText().length() > 3)
            {
                WeightError.setText("Invalid. Length cannot exceed 4 digits and 3 decimal points");
            }
            
            result = false;
        }

        return result;
    }
    
    private void SelectPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectPictureActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Select an image");
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG, JPG, JPEG, and GIF images", "png", "jpg", "jpeg", "gif");
        jfc.addChoosableFileFilter(filter);
        
        int returnValue = jfc.showOpenDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            selectedFile = jfc.getSelectedFile();
            jLabel1.setText(selectedFile.getAbsolutePath());
	}
        
    }//GEN-LAST:event_SelectPictureActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
       selectedFile = null;
       jLabel1.setText("No Picture Selected");
    }//GEN-LAST:event_ResetActionPerformed

    private void WeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightTextActionPerformed

    private void HeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightTextActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AgeCmbBox;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel CriminalIDLabel;
    private javax.swing.JTextPane CriminalIDText;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel EditCriminalInfoLabel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextPane FirstNameText;
    private javax.swing.JLabel HeightError;
    private javax.swing.JTextField HeightText;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel LastNameLabel1;
    private javax.swing.JTextPane LastNameText;
    private javax.swing.JButton Reset;
    private javax.swing.JTextPane SearchText;
    private javax.swing.JButton SelectPicture;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel Weight;
    private javax.swing.JLabel WeightError;
    private javax.swing.JTextField WeightText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbCriminalIDError;
    private javax.swing.JLabel lblFnameError;
    private javax.swing.JLabel lblLnameError;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
