/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ali
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    
    private myDBCon db;
    
    public home(myDBCon db) {
        initComponents();
        clearSelections();
        this.db = db;
        
        //default statistics
        lblStation.setBackground(new Color(255, 255, 255));
        lblOfficer.setBackground(new Color(255, 255, 255));
        lblCriminal.setBackground(new Color(255, 255, 255));
        lblCrimes.setBackground(new Color(255, 255, 255));
        lblCase.setBackground(new Color(255, 255, 255));
        lblStatistics.setBackground(new Color(0, 204, 106));
        
        pnlStation.setVisible(false);
        pnlOfficer.setVisible(false);
        pnlCriminal.setVisible(false);
        pnlCase.setVisible(false);
        pnlStatistics.setVisible(true);
        
        //set background color
        pnlStation.setBackground(new Color(51,51,51));
        pnlOfficer.setBackground(new Color(51,51,51));
        pnlCriminal.setBackground(new Color(51,51,51));
        pnlCrimes.setBackground(new Color(51,51,51));
        pnlCase.setBackground(new Color(51,51,51));
        pnlStatistics.setBackground(new Color(51,51,51));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void clearSelections()
    {
        lblStation.setBackground(new Color(255, 255, 255));
        lblOfficer.setBackground(new Color(255, 255, 255));
        lblCriminal.setBackground(new Color(255, 255, 255));
        lblCrimes.setBackground(new Color(255, 255, 255));
        lblCase.setBackground(new Color(255, 255, 255));
        lblStatistics.setBackground(new Color(255, 255, 255));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnOfficer = new javax.swing.JButton();
        btnCriminal = new javax.swing.JButton();
        btnStation = new javax.swing.JButton();
        btnCase = new javax.swing.JButton();
        lblStation = new javax.swing.JLabel();
        lblCriminal = new javax.swing.JLabel();
        lblOfficer = new javax.swing.JLabel();
        lblCase = new javax.swing.JLabel();
        btnStatistics = new javax.swing.JButton();
        lblStatistics = new javax.swing.JLabel();
        btnCrimes = new javax.swing.JButton();
        lblCrimes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlStation = new javax.swing.JPanel();
        btnAddStation = new javax.swing.JButton();
        btnEditStation = new javax.swing.JButton();
        btnDisplayStation = new javax.swing.JButton();
        btnSearchStation = new javax.swing.JButton();
        pnlOfficer = new javax.swing.JPanel();
        btnAddOfficer = new javax.swing.JButton();
        btnEditOfficer = new javax.swing.JButton();
        btnDisplayOfficer = new javax.swing.JButton();
        btnSearchOfficer = new javax.swing.JButton();
        pnlCriminal = new javax.swing.JPanel();
        btnAddCriminal = new javax.swing.JButton();
        btnEditCriminal = new javax.swing.JButton();
        btnDisplayCriminal = new javax.swing.JButton();
        btnSearchCriminal = new javax.swing.JButton();
        pnlCrimes = new javax.swing.JPanel();
        btnAddCrimes = new javax.swing.JButton();
        btnEditCrimes = new javax.swing.JButton();
        btnDisplayCrimes = new javax.swing.JButton();
        btnSearchCrimes = new javax.swing.JButton();
        pnlCase = new javax.swing.JPanel();
        btnAddCase = new javax.swing.JButton();
        btnEditCase = new javax.swing.JButton();
        btnDisplayCase = new javax.swing.JButton();
        btnSearchCase = new javax.swing.JButton();
        pnlStatistics = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(149, 165, 166));
        jLabel1.setText("You are login as admin");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(52, 152, 219));
        jLabel2.setText("Logout?");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("John Smith");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(149, 165, 166));
        jLabel4.setText("Officer");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("#ID");

        btnOfficer.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnOfficer.setForeground(new java.awt.Color(255, 255, 255));
        btnOfficer.setText("Officer");
        btnOfficer.setBorder(null);
        btnOfficer.setContentAreaFilled(false);
        btnOfficer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOfficer.setMaximumSize(new java.awt.Dimension(87, 25));
        btnOfficer.setMinimumSize(new java.awt.Dimension(87, 25));
        btnOfficer.setPreferredSize(new java.awt.Dimension(87, 25));
        btnOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfficerActionPerformed(evt);
            }
        });

        btnCriminal.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnCriminal.setForeground(new java.awt.Color(255, 255, 255));
        btnCriminal.setText("Criminal");
        btnCriminal.setBorder(null);
        btnCriminal.setContentAreaFilled(false);
        btnCriminal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriminalActionPerformed(evt);
            }
        });

        btnStation.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnStation.setForeground(new java.awt.Color(255, 255, 255));
        btnStation.setText("Station");
        btnStation.setBorder(null);
        btnStation.setContentAreaFilled(false);
        btnStation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStation.setMaximumSize(new java.awt.Dimension(87, 25));
        btnStation.setMinimumSize(new java.awt.Dimension(87, 25));
        btnStation.setPreferredSize(new java.awt.Dimension(87, 25));
        btnStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStationMouseClicked(evt);
            }
        });
        btnStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStationActionPerformed(evt);
            }
        });

        btnCase.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnCase.setForeground(new java.awt.Color(255, 255, 255));
        btnCase.setText("Case");
        btnCase.setBorder(null);
        btnCase.setContentAreaFilled(false);
        btnCase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCase.setMaximumSize(new java.awt.Dimension(87, 25));
        btnCase.setMinimumSize(new java.awt.Dimension(87, 25));
        btnCase.setPreferredSize(new java.awt.Dimension(87, 25));
        btnCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaseActionPerformed(evt);
            }
        });

        lblStation.setBackground(new java.awt.Color(0, 204, 106));
        lblStation.setOpaque(true);

        lblCriminal.setBackground(new java.awt.Color(0, 204, 106));
        lblCriminal.setOpaque(true);

        lblOfficer.setBackground(new java.awt.Color(0, 204, 106));
        lblOfficer.setOpaque(true);

        lblCase.setBackground(new java.awt.Color(0, 204, 106));
        lblCase.setOpaque(true);

        btnStatistics.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnStatistics.setForeground(new java.awt.Color(255, 255, 255));
        btnStatistics.setText("Statistics");
        btnStatistics.setBorder(null);
        btnStatistics.setContentAreaFilled(false);
        btnStatistics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStatistics.setMaximumSize(new java.awt.Dimension(87, 25));
        btnStatistics.setMinimumSize(new java.awt.Dimension(87, 25));
        btnStatistics.setPreferredSize(new java.awt.Dimension(87, 25));
        btnStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticsActionPerformed(evt);
            }
        });

        lblStatistics.setBackground(new java.awt.Color(0, 204, 106));
        lblStatistics.setOpaque(true);

        btnCrimes.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnCrimes.setForeground(new java.awt.Color(255, 255, 255));
        btnCrimes.setText("Crimes");
        btnCrimes.setBorder(null);
        btnCrimes.setContentAreaFilled(false);
        btnCrimes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrimes.setMaximumSize(new java.awt.Dimension(87, 25));
        btnCrimes.setMinimumSize(new java.awt.Dimension(87, 25));
        btnCrimes.setPreferredSize(new java.awt.Dimension(87, 25));
        btnCrimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrimesActionPerformed(evt);
            }
        });

        lblCrimes.setBackground(new java.awt.Color(0, 204, 106));
        lblCrimes.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOfficer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOfficer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCriminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCrimes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(315, 315, 315))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6))
                    .addComponent(jLabel3))
                .addGap(406, 406, 406))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCriminal)
                                    .addComponent(btnOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblStatistics, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                                    .addComponent(lblCase, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                                    .addComponent(lblCriminal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        pnlStation.setBackground(new java.awt.Color(51, 51, 51));

        btnAddStation.setBackground(new java.awt.Color(0, 204, 106));
        btnAddStation.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAddStation.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStation.setText("Add Station");
        btnAddStation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnAddStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStationActionPerformed(evt);
            }
        });

        btnEditStation.setBackground(new java.awt.Color(0, 204, 106));
        btnEditStation.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnEditStation.setForeground(new java.awt.Color(255, 255, 255));
        btnEditStation.setText("Edit Station");
        btnEditStation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnEditStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStationActionPerformed(evt);
            }
        });

        btnDisplayStation.setBackground(new java.awt.Color(0, 204, 106));
        btnDisplayStation.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnDisplayStation.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayStation.setText("Display Station");
        btnDisplayStation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnDisplayStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayStationActionPerformed(evt);
            }
        });

        btnSearchStation.setBackground(new java.awt.Color(0, 204, 106));
        btnSearchStation.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSearchStation.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchStation.setText("Search Station");
        btnSearchStation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnSearchStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStationLayout = new javax.swing.GroupLayout(pnlStation);
        pnlStation.setLayout(pnlStationLayout);
        pnlStationLayout.setHorizontalGroup(
            pnlStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStationLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnAddStation, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplayStation, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditStation, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchStation, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        pnlStationLayout.setVerticalGroup(
            pnlStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStationLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStation, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditStation, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayStation, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStation, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jPanel2.add(pnlStation, "card4");

        pnlOfficer.setBackground(new java.awt.Color(245, 245, 245));

        btnAddOfficer.setBackground(new java.awt.Color(0, 204, 106));
        btnAddOfficer.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAddOfficer.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOfficer.setText("Add Officer");
        btnAddOfficer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnAddOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOfficerActionPerformed(evt);
            }
        });

        btnEditOfficer.setBackground(new java.awt.Color(0, 204, 106));
        btnEditOfficer.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnEditOfficer.setForeground(new java.awt.Color(255, 255, 255));
        btnEditOfficer.setText("Edit Officer");
        btnEditOfficer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnEditOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditOfficerActionPerformed(evt);
            }
        });

        btnDisplayOfficer.setBackground(new java.awt.Color(0, 204, 106));
        btnDisplayOfficer.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnDisplayOfficer.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayOfficer.setText("Display Officer");
        btnDisplayOfficer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnDisplayOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayOfficerActionPerformed(evt);
            }
        });

        btnSearchOfficer.setBackground(new java.awt.Color(0, 204, 106));
        btnSearchOfficer.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSearchOfficer.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchOfficer.setText("Search Officer");
        btnSearchOfficer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnSearchOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOfficerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOfficerLayout = new javax.swing.GroupLayout(pnlOfficer);
        pnlOfficer.setLayout(pnlOfficerLayout);
        pnlOfficerLayout.setHorizontalGroup(
            pnlOfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOfficerLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnAddOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplayOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pnlOfficerLayout.setVerticalGroup(
            pnlOfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOfficerLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlOfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchOfficer, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jPanel2.add(pnlOfficer, "card4");

        pnlCriminal.setBackground(new java.awt.Color(245, 245, 245));

        btnAddCriminal.setBackground(new java.awt.Color(0, 204, 106));
        btnAddCriminal.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAddCriminal.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCriminal.setText("Add Criminal");
        btnAddCriminal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnAddCriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCriminalActionPerformed(evt);
            }
        });

        btnEditCriminal.setBackground(new java.awt.Color(0, 204, 106));
        btnEditCriminal.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnEditCriminal.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCriminal.setText("Edit Criminal");
        btnEditCriminal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnEditCriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCriminalActionPerformed(evt);
            }
        });

        btnDisplayCriminal.setBackground(new java.awt.Color(0, 204, 106));
        btnDisplayCriminal.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnDisplayCriminal.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayCriminal.setText("Display Criminal");
        btnDisplayCriminal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnDisplayCriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCriminalActionPerformed(evt);
            }
        });

        btnSearchCriminal.setBackground(new java.awt.Color(0, 204, 106));
        btnSearchCriminal.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSearchCriminal.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCriminal.setText("Search Criminal");
        btnSearchCriminal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnSearchCriminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCriminalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCriminalLayout = new javax.swing.GroupLayout(pnlCriminal);
        pnlCriminal.setLayout(pnlCriminalLayout);
        pnlCriminalLayout.setHorizontalGroup(
            pnlCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCriminalLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnAddCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplayCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pnlCriminalLayout.setVerticalGroup(
            pnlCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCriminalLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlCriminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCriminal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jPanel2.add(pnlCriminal, "card4");

        pnlCrimes.setBackground(new java.awt.Color(245, 245, 245));

        btnAddCrimes.setBackground(new java.awt.Color(0, 204, 106));
        btnAddCrimes.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAddCrimes.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCrimes.setText("Add Crimes");
        btnAddCrimes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnAddCrimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCrimesActionPerformed(evt);
            }
        });

        btnEditCrimes.setBackground(new java.awt.Color(0, 204, 106));
        btnEditCrimes.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnEditCrimes.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCrimes.setText("Edit Crimes");
        btnEditCrimes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnEditCrimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCrimesActionPerformed(evt);
            }
        });

        btnDisplayCrimes.setBackground(new java.awt.Color(0, 204, 106));
        btnDisplayCrimes.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnDisplayCrimes.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayCrimes.setText("Display Crimes");
        btnDisplayCrimes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnDisplayCrimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCrimesActionPerformed(evt);
            }
        });

        btnSearchCrimes.setBackground(new java.awt.Color(0, 204, 106));
        btnSearchCrimes.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSearchCrimes.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCrimes.setText("Search Crimes");
        btnSearchCrimes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnSearchCrimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCrimesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCrimesLayout = new javax.swing.GroupLayout(pnlCrimes);
        pnlCrimes.setLayout(pnlCrimesLayout);
        pnlCrimesLayout.setHorizontalGroup(
            pnlCrimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrimesLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnAddCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplayCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pnlCrimesLayout.setVerticalGroup(
            pnlCrimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrimesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlCrimesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCrimes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jPanel2.add(pnlCrimes, "card4");

        pnlCase.setBackground(new java.awt.Color(245, 245, 245));

        btnAddCase.setBackground(new java.awt.Color(0, 204, 106));
        btnAddCase.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnAddCase.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCase.setText("Add Case");
        btnAddCase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnAddCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCaseActionPerformed(evt);
            }
        });

        btnEditCase.setBackground(new java.awt.Color(0, 204, 106));
        btnEditCase.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnEditCase.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCase.setText("Edit Case");
        btnEditCase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnEditCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCaseActionPerformed(evt);
            }
        });

        btnDisplayCase.setBackground(new java.awt.Color(0, 204, 106));
        btnDisplayCase.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnDisplayCase.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayCase.setText("Display Case");
        btnDisplayCase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnDisplayCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayCaseActionPerformed(evt);
            }
        });

        btnSearchCase.setBackground(new java.awt.Color(0, 204, 106));
        btnSearchCase.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnSearchCase.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCase.setText("Search Case");
        btnSearchCase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106), new java.awt.Color(0, 204, 106)));
        btnSearchCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCaseLayout = new javax.swing.GroupLayout(pnlCase);
        pnlCase.setLayout(pnlCaseLayout);
        pnlCaseLayout.setHorizontalGroup(
            pnlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaseLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnAddCase, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplayCase, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditCase, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCase, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pnlCaseLayout.setVerticalGroup(
            pnlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaseLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCase, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCase, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisplayCase, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCase, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jPanel2.add(pnlCase, "card4");

        pnlStatistics.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout pnlStatisticsLayout = new javax.swing.GroupLayout(pnlStatistics);
        pnlStatistics.setLayout(pnlStatisticsLayout);
        pnlStatisticsLayout.setHorizontalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        pnlStatisticsLayout.setVerticalGroup(
            pnlStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jPanel2.add(pnlStatistics, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(1014, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStationActionPerformed
        // TODO add your handling code here:
        lblStation.setBackground(new Color(0, 204, 106));
        lblOfficer.setBackground(new Color(255, 255, 255));
        lblCriminal.setBackground(new Color(255, 255, 255));
        lblCrimes.setBackground(new Color(255, 255, 255));
        lblCase.setBackground(new Color(255, 255, 255));
        lblStatistics.setBackground(new Color(255, 255, 255));
        pnlStation.setVisible(true);
        pnlOfficer.setVisible(false);
        pnlCriminal.setVisible(false);
        pnlCrimes.setVisible(false);
        pnlCase.setVisible(false);
        pnlStatistics.setVisible(false);
    }//GEN-LAST:event_btnStationActionPerformed

    private void btnStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStationMouseClicked

    private void btnOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfficerActionPerformed
        // TODO add your handling code here:
        lblStation.setBackground(new Color(255, 255, 255));
        lblOfficer.setBackground(new Color(0, 204, 106));
        lblCriminal.setBackground(new Color(255, 255, 255));
        lblCrimes.setBackground(new Color(255, 255, 255));
        lblCase.setBackground(new Color(255, 255, 255));
        lblStatistics.setBackground(new Color(255, 255, 255));
        pnlStation.setVisible(false);
        pnlOfficer.setVisible(true);
        pnlCriminal.setVisible(false);
        pnlCrimes.setVisible(false);
        pnlCase.setVisible(false);
        pnlStatistics.setVisible(false);
    }//GEN-LAST:event_btnOfficerActionPerformed

    private void btnCriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriminalActionPerformed
        // TODO add your handling code here:
         lblStation.setBackground(new Color(255, 255, 255));
        lblOfficer.setBackground(new Color(255, 255, 255));
        lblCriminal.setBackground(new Color(0, 204, 106));
        lblCrimes.setBackground(new Color(255, 255, 255));
        lblCase.setBackground(new Color(255, 255, 255));
        lblStatistics.setBackground(new Color(255, 255, 255));
        pnlStation.setVisible(false);
        pnlOfficer.setVisible(false);
        pnlCriminal.setVisible(true);
        pnlCrimes.setVisible(false);
        pnlCase.setVisible(false);
        pnlStatistics.setVisible(false);
    }//GEN-LAST:event_btnCriminalActionPerformed

    private void btnCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaseActionPerformed
        // TODO add your handling code here:
         lblStation.setBackground(new Color(255, 255, 255));
        lblOfficer.setBackground(new Color(255, 255, 255));
        lblCriminal.setBackground(new Color(255, 255, 255));
        lblCrimes.setBackground(new Color(255, 255, 255));
        lblCase.setBackground(new Color(0, 204, 106));
        lblStatistics.setBackground(new Color(255, 255, 255));
        pnlStation.setVisible(false);
        pnlOfficer.setVisible(false);
        pnlCriminal.setVisible(false);
        pnlCrimes.setVisible(false);
        pnlCase.setVisible(true);
        pnlStatistics.setVisible(false);
    }//GEN-LAST:event_btnCaseActionPerformed

    private void btnStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticsActionPerformed
         //TODO add your handling code here:
        lblStation.setBackground(new Color(255, 255, 255));
       lblOfficer.setBackground(new Color(255, 255, 255));
       lblCriminal.setBackground(new Color(255, 255, 255));
       lblCrimes.setBackground(new Color(255, 255, 255));
       lblCase.setBackground(new Color(255, 255, 255));
        lblStatistics.setBackground(new Color(0, 204, 106));
        pnlStation.setVisible(false);
        pnlOfficer.setVisible(false);
        pnlCriminal.setVisible(false);
        pnlCrimes.setVisible(false);
        pnlCase.setVisible(false);
        pnlStatistics.setVisible(true);
        
    }//GEN-LAST:event_btnStatisticsActionPerformed

    private void btnEditCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCaseActionPerformed
        try {
            (new EditCases(db)).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditCaseActionPerformed

    private void btnAddStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStationActionPerformed
        try {
            (new AddPoliceStation(db)).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddStationActionPerformed

    private void btnEditStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStationActionPerformed
        (new EditPoliceStation(db)).setVisible(true);
    }//GEN-LAST:event_btnEditStationActionPerformed

    private void btnDisplayStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayStationActionPerformed
        (new DisplayPoliceStation(db, null)).setVisible(true);
    }//GEN-LAST:event_btnDisplayStationActionPerformed

    private void btnAddOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOfficerActionPerformed
        (new AddPoliceOfficer(db)).setVisible(true);
    }//GEN-LAST:event_btnAddOfficerActionPerformed

    private void btnEditOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditOfficerActionPerformed
        (new EditPoliceOfficer(db)).setVisible(true);
    }//GEN-LAST:event_btnEditOfficerActionPerformed

    private void btnDisplayOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayOfficerActionPerformed
        (new DisplayPoliceOfficer(db, null)).setVisible(true);
    }//GEN-LAST:event_btnDisplayOfficerActionPerformed

    private void btnAddCriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCriminalActionPerformed
        (new AddCriminal(db)).setVisible(true);
    }//GEN-LAST:event_btnAddCriminalActionPerformed

    private void btnEditCriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCriminalActionPerformed
        (new EditCriminal(db)).setVisible(true);
    }//GEN-LAST:event_btnEditCriminalActionPerformed

    private void btnDisplayCriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCriminalActionPerformed
        (new DisplayCriminal(db, null)).setVisible(true);
    }//GEN-LAST:event_btnDisplayCriminalActionPerformed

    private void btnAddCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCaseActionPerformed
        try {
            (new AddCases(db)).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddCaseActionPerformed

    private void btnDisplayCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCaseActionPerformed
        try {
            (new DisplayCases(db, null)).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDisplayCaseActionPerformed

    private void btnCrimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrimesActionPerformed
        lblStation.setBackground(new Color(255, 255, 255));
        lblOfficer.setBackground(new Color(255, 255, 255));
        lblCriminal.setBackground(new Color(255, 255, 255));
        lblCrimes.setBackground(new Color(0, 204, 106));
        lblCase.setBackground(new Color(255, 255, 255));
        lblStatistics.setBackground(new Color(255, 255, 255));
        pnlStation.setVisible(false);
        pnlOfficer.setVisible(false);
        pnlCriminal.setVisible(false);
        pnlCrimes.setVisible(true);
        pnlCase.setVisible(false);
        pnlStatistics.setVisible(false);
        
    }//GEN-LAST:event_btnCrimesActionPerformed

    private void btnAddCrimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCrimesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCrimesActionPerformed

    private void btnEditCrimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCrimesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCrimesActionPerformed

    private void btnDisplayCrimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayCrimesActionPerformed
        (new DisplayCrimes(db)).setVisible(true);
    }//GEN-LAST:event_btnDisplayCrimesActionPerformed

    private void btnSearchStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStationActionPerformed
        // TODO add your handling code here:
        (new SearchPoliceStation(db)).setVisible(true);
    }//GEN-LAST:event_btnSearchStationActionPerformed

    private void btnSearchOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOfficerActionPerformed
       new SearchOfficer(db).setVisible(true);
    }//GEN-LAST:event_btnSearchOfficerActionPerformed

    private void btnSearchCriminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCriminalActionPerformed
        // TODO add your handling code here:
       new SearchCriminal(db).setVisible(true);
    }//GEN-LAST:event_btnSearchCriminalActionPerformed

    private void btnSearchCrimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCrimesActionPerformed
       
        
    }//GEN-LAST:event_btnSearchCrimesActionPerformed

    private void btnSearchCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCaseActionPerformed
        // TODO add your handling code here:
        (new SearchCases(db)).setVisible(true);
    }//GEN-LAST:event_btnSearchCaseActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCase;
    private javax.swing.JButton btnAddCrimes;
    private javax.swing.JButton btnAddCriminal;
    private javax.swing.JButton btnAddOfficer;
    private javax.swing.JButton btnAddStation;
    private javax.swing.JButton btnCase;
    private javax.swing.JButton btnCrimes;
    private javax.swing.JButton btnCriminal;
    private javax.swing.JButton btnDisplayCase;
    private javax.swing.JButton btnDisplayCrimes;
    private javax.swing.JButton btnDisplayCriminal;
    private javax.swing.JButton btnDisplayOfficer;
    private javax.swing.JButton btnDisplayStation;
    private javax.swing.JButton btnEditCase;
    private javax.swing.JButton btnEditCrimes;
    private javax.swing.JButton btnEditCriminal;
    private javax.swing.JButton btnEditOfficer;
    private javax.swing.JButton btnEditStation;
    private javax.swing.JButton btnOfficer;
    private javax.swing.JButton btnSearchCase;
    private javax.swing.JButton btnSearchCrimes;
    private javax.swing.JButton btnSearchCriminal;
    private javax.swing.JButton btnSearchOfficer;
    private javax.swing.JButton btnSearchStation;
    private javax.swing.JButton btnStation;
    private javax.swing.JButton btnStatistics;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCase;
    private javax.swing.JLabel lblCrimes;
    private javax.swing.JLabel lblCriminal;
    private javax.swing.JLabel lblOfficer;
    private javax.swing.JLabel lblStation;
    private javax.swing.JLabel lblStatistics;
    private javax.swing.JPanel pnlCase;
    private javax.swing.JPanel pnlCrimes;
    private javax.swing.JPanel pnlCriminal;
    private javax.swing.JPanel pnlOfficer;
    private javax.swing.JPanel pnlStation;
    private javax.swing.JPanel pnlStatistics;
    // End of variables declaration//GEN-END:variables
}
